def get_irregular_verbs():
    return {
        'arise': ['arose', 'arisen'],
        'awake': ['awoke', 'awoken'],
        'be': ['am', 'is', 'are', 'was', 'were', 'being', 'been'],
        'bear': ['bore', 'borne'],
        'beat': ['beat', 'beaten'],
        'become': ['became', 'become'],
        'begin': ['began', 'begun'],
        'bend': ['bent'],
        'bet': ['bet'],
        'bind': ['bound'],
        'bite': ['bit', 'bitten'],
        'bleed': ['bled'],
        'blow': ['blew', 'blown'],
        'break': ['broke', 'broken'],
        'bring': ['brought'],
        'build': ['built'],
        'burn': ['burnt', 'burned'],
        'burst': ['burst'],
        'buy': ['bought'],
        'catch': ['caught'],
        'choose': ['chose', 'chosen'],
        'come': ['came', 'come'],
        'cost': ['cost'],
        'cut': ['cut'],
        'deal': ['dealt'],
        'dig': ['dug'],
        'do': ['did', 'done', 'doing'],
        'draw': ['drew', 'drawn'],
        'dream': ['dreamt', 'dreamed'],
        'drink': ['drank', 'drunk'],
        'drive': ['drove', 'driven'],
        'eat': ['ate', 'eaten'],
        'fall': ['fell', 'fallen'],
        'feed': ['fed'],
        'feel': ['felt'],
        'fight': ['fought'],
        'find': ['found'],
        'fly': ['flew', 'flown'],
        'forget': ['forgot', 'forgotten'],
        'forgive': ['forgave', 'forgiven'],
        'freeze': ['froze', 'frozen'],
        'get': ['got', 'gotten'],
        'give': ['gave', 'given'],
        'go': ['went', 'gone', 'going'],
        'grow': ['grew', 'grown'],
        'hang': ['hung'],
        'have': ['had'],
        'hear': ['heard'],
        'hide': ['hid', 'hidden'],
        'hit': ['hit'],
        'hold': ['held'],
        'hurt': ['hurt'],
        'keep': ['kept'],
        'know': ['knew', 'known'],
        'lay': ['laid'],
        'lead': ['led'],
        'leave': ['left'],
        'lend': ['lent'],
        'let': ['let'],
        'lie': ['lay', 'lain'],
        'lose': ['lost'],
        'make': ['made'],
        'mean': ['meant'],
        'meet': ['met'],
        'pay': ['paid'],
        'put': ['put'],
        'read': ['read'],
        'ride': ['rode', 'ridden'],
        'ring': ['rang', 'rung'],
        'rise': ['rose', 'risen'],
        'run': ['ran', 'run'],
        'say': ['said'],
        'see': ['saw', 'seen'],
        'sell': ['sold'],
        'send': ['sent'],
        'set': ['set'],
        'shake': ['shook', 'shaken'],
        'shine': ['shone'],
        'shoot': ['shot'],
        'show': ['showed', 'shown'],
        'shut': ['shut'],
        'sing': ['sang', 'sung'],
        'sink': ['sank', 'sunk'],
        'sit': ['sat'],
        'sleep': ['slept'],
        'speak': ['spoke', 'spoken'],
        'spend': ['spent'],
        'stand': ['stood'],
        'steal': ['stole', 'stolen'],
        'swim': ['swam', 'swum'],
        'take': ['took', 'taken'],
        'teach': ['taught'],
        'tear': ['tore', 'torn'],
        'tell': ['told'],
        'think': ['thought'],
        'throw': ['threw', 'thrown'],
        'understand': ['understood'],
        'wake': ['woke', 'woken'],
        'wear': ['wore', 'worn'],
        'win': ['won'],
        'write': ['wrote', 'written'],
        # Add more irregular verbs as needed
    }
